//! The `chapter_scan` reading path against real files and real storage:
//! an ffmpeg that actually opens a container, and rows that actually
//! land in an imported band.
//!
//! The parser's own grammar is covered by unit tests beside it
//! (`jobs::chapter_ffmetadata`), over strings. What those cannot tell
//! anybody is whether the strings are the ones ffmpeg prints — and on
//! the Matroska fixture they are emphatically not what a reader would
//! guess: the file is *written* with millisecond chapter times and comes
//! back declaring `TIMEBASE=1/1000000000`, so a parser that assumed
//! milliseconds would be wrong by a factor of a million on the first
//! real file it met. That is the gap this file exists to close.
//!
//! # Fixtures, and the numbers being managed twice
//!
//! `chaptered.mkv` and `chaptered.m4a` are generated by
//! `scripts/gen-test-fixtures.py`, which declares the same timings this
//! file asserts. The duplication is deliberate and is the header of that
//! script's standing policy: a test that read its expectations out of
//! the fixture would pass against a fixture with no chapters at all.
//!
//! Every other media fixture in the workspace is a negative case here,
//! and one of them is asserted as such below — "declares no chapters"
//! and "could not be read" are different outcomes and only one of them
//! leaves a band behind.
//!
//! # No skip when ffmpeg is missing
//!
//! These panic with the install instruction instead, following
//! `thumb_ffmpeg`'s fixture test: a skipped gate reads as a passed one
//! in a summary line, and this repository has no CI to notice the
//! difference.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use asterism_core::application_support::replace_imported_chapters;
use asterism_core::domain::asset::Asset;
use asterism_core::domain::attribution::AttributionContext;
use asterism_core::domain::material::Material;
use asterism_core::domain::material_layer::{LayerOrigin, LayerRole};
use asterism_core::domain::persona::Persona;
use asterism_core::domain::repository::{
    AssetRepository, ChapterMarkRepository, MaterialLayerRepository, PersonaRepository,
};
use asterism_core::domain::source_locator::LocalPath;
use asterism_core::domain::value::{AssetId, Modality, PersonaId, SourceKind, SourceRef};
use asterism_infra::jobs::chapter_ffmetadata::{ChapterProbe, ChapterReading, read_chapters};
use asterism_infra::jobs::thumb_ffmpeg::ffmpeg_binary;
use asterism_infra::sqlite::open_and_migrate_in_memory;
use asterism_infra::sqlite::repo::{
    SqliteAssetRepository, SqliteChapterMarkRepository, SqliteMaterialLayerRepository,
    SqlitePersonaRepository,
};
use chrono::Utc;
use rusqlite_isle::AsyncIsleDriver;

/// The sections `gen-test-fixtures.py` bakes into `chaptered.mkv`, in
/// milliseconds — the same list, stated again on this side.
const MKV_CHAPTERS: [(u64, u64, &str); 3] = [
    (0, 2_000, "Opening"),
    // Untitled on purpose: the muxer writes no `title=` line for it at
    // all, so this is the one section proving an absent title reads as
    // an empty label rather than as a refusal.
    (2_000, 4_000, ""),
    (4_000, 6_000, "Finale"),
];

/// The same, for `chaptered.m4a` — a different container family, whose
/// chapter times come back on a different timebase.
const M4A_CHAPTERS: [(u64, u64, &str); 2] = [(0, 3_000, "Side A"), (3_000, 6_000, "Side B")];

fn fixture(crate_name: &str, file: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join(crate_name)
        .join("tests/fixtures")
        .join(file)
}

fn chaptered_mkv() -> PathBuf {
    fixture("asterism-importer-video", "chaptered.mkv")
}

fn chaptered_m4a() -> PathBuf {
    fixture("asterism-importer-audio", "chaptered.m4a")
}

/// Reads a fixture through the real binary, insisting on an answer.
fn read_fixture(path: &Path) -> ChapterReading {
    ffmpeg_binary()
        .expect("ffmpeg is required for this test: brew install ffmpeg (or set $ASTERISM_FFMPEG)");
    assert!(
        path.is_file(),
        "{} is missing — run `python3 scripts/gen-test-fixtures.py`",
        path.display()
    );
    match read_chapters(&path.to_string_lossy()) {
        ChapterProbe::Read(reading) => reading,
        ChapterProbe::Unreadable(why) => panic!("the fixture should be readable: {why}"),
    }
}

fn declared(reading: &ChapterReading) -> Vec<(u64, Option<u64>, String)> {
    reading
        .chapters
        .iter()
        .map(|c| (c.span.start_ms(), c.span.end_ms(), c.label.clone()))
        .collect()
}

fn expected(chapters: &[(u64, u64, &str)]) -> Vec<(u64, Option<u64>, String)> {
    chapters
        .iter()
        .map(|(start, end, label)| (*start, Some(*end), (*label).to_string()))
        .collect()
}

/// A Matroska file's `Chapters` segment, read end to end.
///
/// The timebase is the claim. ffmpeg reports this file's chapters in
/// **nanoseconds**, so every number below is the result of the
/// conversion `TimelineSpan`'s doc demands of anything arriving on
/// another clock — not a number copied out of the container.
#[test]
fn a_matroska_declares_its_sections_and_they_arrive_in_milliseconds() {
    let reading = read_fixture(&chaptered_mkv());
    assert!(
        reading.refused.is_empty(),
        "nothing in this file should be unrepresentable: {:?}",
        reading.refused
    );
    assert_eq!(declared(&reading), expected(&MKV_CHAPTERS));
}

/// The MP4 family's spelling, which is a different one: chapters live in
/// a chapter track rather than in a segment, and ffmpeg reports them on
/// a millisecond timebase.
///
/// Here so that the reading is exercised against two container families
/// rather than one — a parser that happened to work on Matroska and not
/// on MP4 would pass a suite that only carried the first.
#[test]
fn an_mp4_container_declares_its_sections_too() {
    let reading = read_fixture(&chaptered_m4a());
    assert!(reading.refused.is_empty(), "{:?}", reading.refused);
    assert_eq!(declared(&reading), expected(&M4A_CHAPTERS));
}

/// A file that declares nothing reads as an empty list, **not** as a
/// failure — which is what makes the empty imported band the job files
/// for it an answer rather than a placeholder.
///
/// `testsrc.mp4` is one of the fixtures generated for the video parser;
/// nothing about it was arranged for this test, which is the point.
#[test]
fn a_file_with_no_chapter_list_reads_as_nothing_declared() {
    let reading = read_fixture(&fixture("asterism-importer-video", "testsrc.mp4"));
    assert_eq!(
        reading,
        ChapterReading::default(),
        "no chapters and no refusals is a complete answer"
    );
}

/// A file that is not there is `Unreadable`, and the distinction is the
/// one the whole backfill rests on: an unreadable material must stay in
/// the walk, so it must not come back as "declares nothing".
#[test]
fn a_file_that_cannot_be_opened_is_not_a_file_that_declares_nothing() {
    ffmpeg_binary()
        .expect("ffmpeg is required for this test: brew install ffmpeg (or set $ASTERISM_FFMPEG)");
    let missing = std::env::temp_dir().join("asterism-no-such-clip.mkv");
    assert!(!missing.exists(), "the test needs this path to be empty");
    match read_chapters(&missing.to_string_lossy()) {
        ChapterProbe::Unreadable(_) => {}
        ChapterProbe::Read(reading) => {
            panic!("a missing file must not answer the question: {reading:?}")
        }
    }
}

struct Fixture {
    assets: Arc<SqliteAssetRepository>,
    personas: Arc<SqlitePersonaRepository>,
    layers: Arc<SqliteMaterialLayerRepository>,
    chapters: Arc<SqliteChapterMarkRepository>,
    driver: AsyncIsleDriver,
}

impl Fixture {
    async fn open() -> Self {
        let (isle, driver) = open_and_migrate_in_memory().await.unwrap();
        Self {
            assets: Arc::new(SqliteAssetRepository::new(isle.clone())),
            personas: Arc::new(SqlitePersonaRepository::new(isle.clone())),
            layers: Arc::new(SqliteMaterialLayerRepository::new(isle.clone())),
            chapters: Arc::new(SqliteChapterMarkRepository::new(isle.clone())),
            driver,
        }
    }

    async fn seed_persona(&self) -> PersonaId {
        let persona = Persona::new("P", None).unwrap();
        self.personas.save(&persona).await.unwrap();
        persona.id
    }

    /// An asset whose primary material is the file at `path`, with the
    /// mime guessed from it the way ingest guesses it.
    async fn seed_asset(&self, persona: PersonaId, path: &str) -> AssetId {
        let attribution = AttributionContext::asserted(None, None).unwrap();
        let mut asset = Asset::new(
            persona,
            SourceRef::new(SourceKind::new(SourceKind::FS).unwrap(), path).unwrap(),
            Some(Modality::new("video").unwrap()),
            Utc::now(),
            &attribution,
        );
        // `LocalPath::try_from(..).into()` rather than
        // `SourceLocator::try_from(&str)`, which reads the *stored*
        // spelling: the pieces are in hand here, so there is nothing to
        // parse back out of a tag.
        asset
            .attach_material(Material::primary(
                LocalPath::try_from(PathBuf::from(path)).unwrap().into(),
                None,
                Utc::now(),
            ))
            .unwrap();
        self.assets.save(&asset).await.unwrap();
        asset.id
    }

    async fn close(self) {
        self.driver.shutdown().await.unwrap();
    }
}

/// The whole path in one test: a real file is read by a real ffmpeg, and
/// what it declared is what the imported band ends up holding.
///
/// The band's `origin` and `role` are asserted rather than assumed. They
/// are what the immutability guard reads — a reading that landed in a
/// `User` band would be editable and would be destroyed by the next
/// re-probe, and nothing else in this path would have noticed.
#[tokio::test]
async fn a_real_reading_lands_as_rows_in_the_imported_structure_band() {
    let reading = read_fixture(&chaptered_mkv());
    let fx = Fixture::open().await;
    let persona = fx.seed_persona().await;
    let asset = fx
        .seed_asset(persona, &chaptered_mkv().to_string_lossy())
        .await;

    let band = replace_imported_chapters(
        fx.layers.as_ref(),
        fx.chapters.as_ref(),
        &asset,
        0,
        &reading.chapters,
    )
    .await
    .expect("the reading is filed");
    assert_eq!(band.origin, LayerOrigin::Imported);
    assert_eq!(band.role, LayerRole::Structure);

    let stored = fx.chapters.list_by_layer(&band.id).await.unwrap();
    assert_eq!(
        stored
            .iter()
            .map(|c| (c.span.start_ms(), c.span.end_ms(), c.label.clone(), c.ord))
            .collect::<Vec<_>>(),
        MKV_CHAPTERS
            .iter()
            .enumerate()
            .map(|(i, (start, end, label))| (*start, Some(*end), (*label).to_string(), i as u32))
            .collect::<Vec<_>>(),
        "reading order is the container's, and `ord` is the position in it"
    );

    fx.close().await;
}

/// Re-reading the same file replaces the band's contents instead of
/// adding to them.
///
/// The job is enqueued by the ingest fan-out *and* by a backfill walk
/// that can reach the same material, so running twice is an ordinary
/// event rather than a fault. Without replacement the second run would
/// double every chapter, and the surface would show each section twice
/// with no way to tell which row came from which reading.
#[tokio::test]
async fn reading_the_same_file_twice_replaces_rather_than_accumulates() {
    let reading = read_fixture(&chaptered_mkv());
    let fx = Fixture::open().await;
    let persona = fx.seed_persona().await;
    let asset = fx
        .seed_asset(persona, &chaptered_mkv().to_string_lossy())
        .await;

    let first = replace_imported_chapters(
        fx.layers.as_ref(),
        fx.chapters.as_ref(),
        &asset,
        0,
        &reading.chapters,
    )
    .await
    .unwrap();
    let before: Vec<_> = fx
        .chapters
        .list_by_layer(&first.id)
        .await
        .unwrap()
        .into_iter()
        .map(|c| c.id)
        .collect();

    let second = replace_imported_chapters(
        fx.layers.as_ref(),
        fx.chapters.as_ref(),
        &asset,
        0,
        &reading.chapters,
    )
    .await
    .unwrap();
    assert_eq!(second.id, first.id, "the band is resolved, not re-created");

    let after = fx.chapters.list_by_layer(&second.id).await.unwrap();
    assert_eq!(after.len(), MKV_CHAPTERS.len(), "no accumulation");
    assert!(
        after.iter().all(|c| !before.contains(&c.id)),
        "ids are minted fresh on every reading, so a held id is honestly gone"
    );

    fx.close().await;
}

/// The backfill walk's two predicates, and the property the walk's
/// termination rests on.
///
/// A material is offered while it can carry chapters and has no imported
/// structure band, and filing one — **including an empty one** — takes
/// it out. That is the whole stop condition: a walk selecting on "has no
/// chapters" instead would hand back every chapterless clip on every
/// pass, and each offer spawns an ffmpeg.
#[tokio::test]
async fn the_backfill_offers_a_timed_material_once_and_then_stops() {
    let fx = Fixture::open().await;
    let persona = fx.seed_persona().await;
    let video = fx.seed_asset(persona, "/library/clip.mkv").await;
    let audio = fx.seed_asset(persona, "/library/song.m4a").await;
    // A still has no playback timeline, so nothing a chapter could
    // divide — it must never reach an ffmpeg.
    let _image = fx.seed_asset(persona, "/library/plate.png").await;

    let offered = |page: Vec<asterism_core::domain::repository::ChapterScanCandidate>| {
        let mut ids: Vec<AssetId> = page.into_iter().map(|c| c.asset_id).collect();
        ids.sort();
        ids
    };
    let mut both = vec![video, audio];
    both.sort();
    assert_eq!(
        offered(
            fx.assets
                .scan_chapter_scan_candidates(None, 50)
                .await
                .unwrap()
        ),
        both,
        "video and audio are offered; the still is not"
    );

    // The video's file declares nothing — the empty band is still the
    // answer, and it is what retires the row.
    replace_imported_chapters(fx.layers.as_ref(), fx.chapters.as_ref(), &video, 0, &[])
        .await
        .unwrap();
    assert_eq!(
        offered(
            fx.assets
                .scan_chapter_scan_candidates(None, 50)
                .await
                .unwrap()
        ),
        vec![audio],
        "an empty band is a reading, so the material has been answered"
    );

    // A band the *person* opened is not a reading and must not retire
    // anything: the walk names the imported one specifically.
    let mine = asterism_core::domain::material_layer::MaterialLayer::new(
        audio,
        0,
        LayerOrigin::User,
        LayerRole::Structure,
        false,
        1,
    )
    .unwrap();
    fx.layers.save(&mine).await.unwrap();
    assert_eq!(
        offered(
            fx.assets
                .scan_chapter_scan_candidates(None, 50)
                .await
                .unwrap()
        ),
        vec![audio],
        "a person's own band is not the file's statement about itself"
    );

    fx.close().await;
}

/// The walk is resumable from the composite `(asset_id, ord)` cursor,
/// and the cursor is exclusive.
#[tokio::test]
async fn the_backfill_walk_resumes_after_its_cursor() {
    let fx = Fixture::open().await;
    let persona = fx.seed_persona().await;
    let mut seeded = [
        fx.seed_asset(persona, "/library/a.mkv").await,
        fx.seed_asset(persona, "/library/b.mkv").await,
        fx.seed_asset(persona, "/library/c.mkv").await,
    ];
    seeded.sort();

    let first = fx
        .assets
        .scan_chapter_scan_candidates(None, 2)
        .await
        .unwrap();
    assert_eq!(
        first.iter().map(|c| c.asset_id).collect::<Vec<_>>(),
        seeded[..2].to_vec(),
        "page one, in id order"
    );

    let rest = fx
        .assets
        .scan_chapter_scan_candidates(Some((&seeded[1], 0)), 2)
        .await
        .unwrap();
    assert_eq!(
        rest.iter().map(|c| c.asset_id).collect::<Vec<_>>(),
        vec![seeded[2]],
        "the cursor row itself is behind the walk, not in front of it"
    );

    fx.close().await;
}
