// This file is auto-generated by schema-bridge

export type RegisterPersonaCommand = { name: string; pack_id: string | null; };

export type ArchivePersonaCommand = { persona_id: string; archived: boolean; };

export type TrashPersonaCommand = { persona_id: string; };

export type RestorePersonaCommand = { persona_id: string; };

export type PurgePersonaCommand = { persona_id: string; };

export type AddAssetCommand = { persona_id: string; source_kind: string; locator: string; modality: string | null; occurred_at_ms: number; session_id: string | null; external_session_key: string | null; external_key: string | null; bundle_id: string | null; labels: string[]; register_note: string | null; platform: string | null; file_size_bytes: number | null; duration_ms: number | null; width_px: number | null; height_px: number | null; extra_json: string | null; cover_hint: string | null; auto_organize_base_dir: string | null; derived_from: string | null; author_kind: string | null; author_subject: string | null; operator_ai: string | null; on_duplicate: 'ask' | 'fold' | 'separate' | null; declared_content_hash: string | null; album_meta: Record<string, string>; };

export type AddAssetBatchCommand = { items: { persona_id: string; source_kind: string; locator: string; modality: string | null; occurred_at_ms: number; session_id: string | null; external_session_key: string | null; external_key: string | null; bundle_id: string | null; labels: string[]; register_note: string | null; platform: string | null; file_size_bytes: number | null; duration_ms: number | null; width_px: number | null; height_px: number | null; extra_json: string | null; cover_hint: string | null; auto_organize_base_dir: string | null; derived_from: string | null; author_kind: string | null; author_subject: string | null; operator_ai: string | null; on_duplicate: 'ask' | 'fold' | 'separate' | null; declared_content_hash: string | null; album_meta: Record<string, string>; }[]; auto_organize_base_dir: string | null; };

export type AddAssetBatchResult = { succeeded: string[]; failed: string[]; success_count: number; failure_count: number; };

export type UpdateAssetMetaCommand = { asset_id: string; labels: string[] | null; register_note: string | null; cover: string | null; title: string | null; rating: number | null; modality: string | null; bundle_id: string | null; };

export type UpdateAssetMetaBatchCommand = { items: { asset_id: string; labels: string[] | null; register_note: string | null; cover: string | null; title: string | null; rating: number | null; modality: string | null; bundle_id: string | null; }[]; };

export type UpdateAssetMetaBatchResult = { succeeded: { id: string; persona_id: string; source_kind: string; locator: string; file_size_bytes: number | null; platform: string | null; mime: string | null; media: string; content_hash: string | null; modality: string | null; labels: string[]; occurred_at_ms: number; container_id: string | null; title: string | null; bundle_id: string | null; role: string; cover: string | null; keywords: string[]; register_note: string | null; visibility_restricted: boolean; visibility_sharing: string[]; duration_ms: number | null; width_px: number | null; height_px: number | null; rating: number | null; palette: string[] | null; extra_json: string | null; created_at_ms: number; updated_at_ms: number; author_kind: string | null; author_subject: string | null; operator_ai: string | null; attributed_via: string | null; on_duplicate: string | null; folded_into: string | null; fold_policy: string; } | null[]; failed: string[]; success_count: number; failure_count: number; };

export type TrashAssetCommand = { asset_id: string; };

export type RestoreAssetCommand = { asset_id: string; };

export type PurgeAssetCommand = { asset_id: string; };

export type EmptyTrashResult = { purged: number; skipped: number; };

export type DeclareProvenanceCommand = { asset_id: string; derived_from: string; relation: string | null; operator_ai: string | null; };

export type DeclareAssetMetaCommand = { asset_id: string; key: string; value: string | null; operator_ai: string | null; };

export type RebuildEdgesCommand = { asset_id: string; };

export type CancelJobCommand = { job_id: string; };

export type CreateGroupCommand = { persona_id: string; name: string; description: string | null; };

export type TrashGroupCommand = { group_id: string; };

export type RestoreGroupCommand = { group_id: string; };

export type PurgeGroupCommand = { group_id: string; };

export type AddAssetToGroupCommand = { asset_id: string; group_id: string; };

export type RemoveAssetFromGroupCommand = { asset_id: string; group_id: string; };

export type ReorderGroupAssetsCommand = { group_id: string; ordered_asset_ids: string[]; };

export type RenameGroupCommand = { group_id: string; name: string; };

export type MoveGroupToDirCommand = { group_id: string; dir_id: string | null; };

export type LinkGroupCommand = { parent_group_id: string; child_group_id: string; };

export type UnlinkGroupCommand = { parent_group_id: string; child_group_id: string; };

export type ReorderGroupChildrenCommand = { parent_group_id: string; ordered_child_ids: string[]; };

export type CreateDirCommand = { persona_id: string; parent_id: string | null; name: string; };

export type RenameDirCommand = { dir_id: string; name: string; };

export type MoveDirCommand = { dir_id: string; new_parent_id: string | null; };

export type DeleteDirCommand = { dir_id: string; };

export type SetPersonaThemeCommand = { persona_id: string; wallpaper_asset_id: string | null; };

export type DeletePersonaThemeCommand = { persona_id: string; };

export type SetPersonaProfileCommand = { persona_id: string; avatar_asset_id: string | null; bio_short: string | null; role_tag: string | null; };

export type DeletePersonaProfileCommand = { persona_id: string; };

export type CreateModalityCommand = { slug: string; label: string; terminal: boolean; sort_order: number; hidden: boolean; cover_template: string | null; };

export type UpdateModalityCommand = { slug: string; label: string | null; terminal: boolean | null; sort_order: number | null; hidden: boolean | null; cover_template: string | null; };

export type DeleteModalityCommand = { slug: string; };

export type SetSettingCommand = { key: string; value_json: string; };

export type ResetSettingCommand = { key: string; };

export type RenameSessionCommand = { id: string; title: string | null; };

export type PatchSessionMetadataCommand = { id: string; title: string | null; note: string | null; cover_hint: string | null; };

export type DeleteSessionCommand = { id: string; };

export type PasteImageImportCommand = { persona_id: string; bytes: number[]; mime_type: string; };

export type ReorderPersonasCommand = { ordered_ids: string[]; };

export type AttachTagCommand = { asset_id: string; name: string; };

export type DetachTagCommand = { asset_id: string; tag_id: string; };

export type AttachTagBatchCommand = { items: { asset_id: string; name: string; }[]; };

export type AttachTagBatchResult = { succeeded: { id: string; name: string; axis: string | null; } | null[]; failed: string[]; success_count: number; failure_count: number; };

export type DetachTagBatchCommand = { items: { asset_id: string; tag_id: string; }[]; };

export type DetachTagBatchResult = { succeeded: boolean[]; failed: string[]; success_count: number; failure_count: number; };

export type PromoteTagToGroupCommand = { tag_id: string; persona_id: string; name: string; description: string | null; dir_id: string | null; };

export type PromoteTagToGroupResult = { group_id: string; persona_id: string; name: string; asset_count: number; };

export type CreateDispatchCommand = { snapshot_id: string; exporter_slug: string; action: string; params_json: string; operator_ai: string | null; pursuit_id: string | null; };

export type PromoteSnapshotToGroupCommand = { snapshot_id: string; name: string; description: string | null; dir_id: string | null; };

export type PromoteSnapshotToGroupResult = { group_id: string; snapshot_id: string; name: string; asset_count: number; };

export type PromoteVolatileSelectionCommand = { persona_id: string; asset_ids: string[]; name: string; description: string | null; dir_id: string | null; };

export type CreateQueryGroupCommand = { persona_id: string; name: string; query_json: string; };

export type UpdateQueryGroupQueryCommand = { group_id: string; query_json: string; };

export type DispatchRunCommand = { persona_id: string; group_id: string | null; asset_ids: string[]; exporter_slug: string; action: string; params_json: string; operator_ai: string | null; pursuit_id: string | null; };

export type RedispatchCommand = { dispatch_id: string; pursuit_id: string | null; };

export type CreateSavedQueryCommand = { persona_id: string; name: string; filter_json: string; sort_json: string; position: number | null; };

export type RenameSavedQueryCommand = { id: string; name: string; };

export type DeleteSavedQueryCommand = { id: string; };

export type PostAssetCommentCommand = { asset_id: string; author_kind: string; author_persona_id: string | null; body: string; };

export type EditAssetCommentCommand = { asset_id: string; comment_id: string; body: string; };

export type DeleteAssetCommentCommand = { comment_id: string; };

export type PostMaterialMarkCommand = { asset_id: string; anchor_kind: string; start_ms: number | null; end_ms: number | null; author_kind: string; author_persona_id: string | null; body: string; };

export type EditMaterialMarkCommand = { asset_id: string; mark_id: string; body: string; };

export type DeleteMaterialMarkCommand = { mark_id: string; };

export type CreateMaterialLayerCommand = { asset_id: string; material_ord: number | null; role: string; ord: number; };

export type SetDefaultMaterialLayerCommand = { layer_id: string; };

export type DeleteMaterialLayerCommand = { layer_id: string; };

export type PostChapterMarkCommand = { layer_id: string; start_ms: number; end_ms: number | null; label: string; ord: number; };

export type EditChapterMarkCommand = { layer_id: string; chapter_id: string; label: string; start_ms: number | null; end_ms: number | null; ord: number | null; };

export type DeleteChapterMarkCommand = { layer_id: string; chapter_id: string; };

export type RecordEventCommand = { kind: string; persona_id: string | null; duration_ms: number | null; payload_json: string | null; };

export type RecordDiagCommand = { level: string; event: string; message: string; attrs_json: string | null; };

export type ResolveDuplicateConflictCommand = { conflict_id: string; resolution: 'folded' | 'kept'; keeper_id: string | null; };

export type MergeAssetsCommand = { keeper_id: string; discard_ids: string[]; member_ids: string[]; dry_run: boolean; };

export type ListAssetsQuery = { viewer_subject: string | null; persona_id: string | null; modality: string | null; occurred_from_ms: number | null; occurred_until_ms: number | null; created_from_ms: number | null; created_until_ms: number | null; updated_from_ms: number | null; updated_until_ms: number | null; tag_ids: string[]; tag_match: 'any' | 'all'; group_ids: string[]; session_id: string | null; label: string | null; text_match: string | null; format: string | null; color: string | null; rating_min: number | null; rating_max: number | null; duration_min_ms: number | null; duration_max_ms: number | null; size_min_bytes: number | null; size_max_bytes: number | null; pixels_min: number | null; pixels_max: number | null; trash: string | null; album_meta_key: string | null; album_meta_value: string | null; sort: { target: 'occurred_at' | 'created_at' | 'updated_at' | 'persona' | 'modality' | 'tag' | 'group' | 'cover' | 'rating' | 'duration' | 'file_size' | 'pixels'; order: 'alpha' | 'ordered' | 'updated'; reverse: boolean; collation: string | null; } | null; offset: number; limit: number; };

export type SearchAssetsQuery = { text: string; filter: { viewer_subject: string | null; persona_id: string | null; modality: string | null; occurred_from_ms: number | null; occurred_until_ms: number | null; created_from_ms: number | null; created_until_ms: number | null; updated_from_ms: number | null; updated_until_ms: number | null; tag_ids: string[]; tag_match: 'any' | 'all'; group_ids: string[]; session_id: string | null; label: string | null; text_match: string | null; format: string | null; color: string | null; rating_min: number | null; rating_max: number | null; duration_min_ms: number | null; duration_max_ms: number | null; size_min_bytes: number | null; size_max_bytes: number | null; pixels_min: number | null; pixels_max: number | null; trash: string | null; album_meta_key: string | null; album_meta_value: string | null; sort: { target: 'occurred_at' | 'created_at' | 'updated_at' | 'persona' | 'modality' | 'tag' | 'group' | 'cover' | 'rating' | 'duration' | 'file_size' | 'pixels'; order: 'alpha' | 'ordered' | 'updated'; reverse: boolean; collation: string | null; } | null; offset: number; limit: number; }; };

export type RandomAssetsQuery = { filter: { viewer_subject: string | null; persona_id: string | null; modality: string | null; occurred_from_ms: number | null; occurred_until_ms: number | null; created_from_ms: number | null; created_until_ms: number | null; updated_from_ms: number | null; updated_until_ms: number | null; tag_ids: string[]; tag_match: 'any' | 'all'; group_ids: string[]; session_id: string | null; label: string | null; text_match: string | null; format: string | null; color: string | null; rating_min: number | null; rating_max: number | null; duration_min_ms: number | null; duration_max_ms: number | null; size_min_bytes: number | null; size_max_bytes: number | null; pixels_min: number | null; pixels_max: number | null; trash: string | null; album_meta_key: string | null; album_meta_value: string | null; sort: { target: 'occurred_at' | 'created_at' | 'updated_at' | 'persona' | 'modality' | 'tag' | 'group' | 'cover' | 'rating' | 'duration' | 'file_size' | 'pixels'; order: 'alpha' | 'ordered' | 'updated'; reverse: boolean; collation: string | null; } | null; offset: number; limit: number; }; k: number | null; };

export type GetAssetDetailQuery = { asset_id: string; viewer_subject: string | null; };

export type GetJobStatusQuery = { job_id: string; };

export type ListEventsQuery = { kind: string | null; since_ms: number | null; until_ms: number | null; limit: number; };

export type PersonaDto = { id: string; pack_id: string | null; name: string; accent_color: string | null; display_order: number; archived: boolean; created_at_ms: number; updated_at_ms: number; };

export type PersonaThemeDto = { persona_id: string; wallpaper_asset_id: string | null; updated_at_ms: number; };

export type PersonaProfileDto = { persona_id: string; avatar_asset_id: string | null; bio_short: string | null; role_tag: string | null; updated_at_ms: number; };

export type AssetCardDto = { id: string; persona_id: string; modality: string | null; occurred_at_ms: number; cover: string | null; labels: string[]; file_size_bytes: number | null; duration_ms: number | null; pixel_count: number | null; mime: string | null; media: string; source_locator: string; group_ids: string[]; primary_group_position: number | null; created_at_ms: number; updated_at_ms: number; rating: number | null; palette: string[] | null; has_note: boolean; has_thread: boolean; role: string; title: string | null; member_count: number; score: number | null; snippet: string | null; author_kind: string | null; author_subject: string | null; operator_ai: string | null; };

export type AssetPageDto = { items: { id: string; persona_id: string; modality: string | null; occurred_at_ms: number; cover: string | null; labels: string[]; file_size_bytes: number | null; duration_ms: number | null; pixel_count: number | null; mime: string | null; media: string; source_locator: string; group_ids: string[]; primary_group_position: number | null; created_at_ms: number; updated_at_ms: number; rating: number | null; palette: string[] | null; has_note: boolean; has_thread: boolean; role: string; title: string | null; member_count: number; score: number | null; snippet: string | null; author_kind: string | null; author_subject: string | null; operator_ai: string | null; }[]; offset: number; limit: number; total: number | null; };

export type RetrievedPageDto = { items: { id: string; persona_id: string; modality: string | null; occurred_at_ms: number; cover: string | null; labels: string[]; file_size_bytes: number | null; duration_ms: number | null; pixel_count: number | null; mime: string | null; media: string; source_locator: string; group_ids: string[]; primary_group_position: number | null; created_at_ms: number; updated_at_ms: number; rating: number | null; palette: string[] | null; has_note: boolean; has_thread: boolean; role: string; title: string | null; member_count: number; score: number | null; snippet: string | null; author_kind: string | null; author_subject: string | null; operator_ai: string | null; }[]; offset: number; limit: number; matched: number; candidates_considered: number; truncated: boolean; };

export type RetrievedIdsDto = { ids: string[]; candidates_considered: number; truncated: boolean; };

export type SampledPageDto = { items: { id: string; persona_id: string; modality: string | null; occurred_at_ms: number; cover: string | null; labels: string[]; file_size_bytes: number | null; duration_ms: number | null; pixel_count: number | null; mime: string | null; media: string; source_locator: string; group_ids: string[]; primary_group_position: number | null; created_at_ms: number; updated_at_ms: number; rating: number | null; palette: string[] | null; has_note: boolean; has_thread: boolean; role: string; title: string | null; member_count: number; score: number | null; snippet: string | null; author_kind: string | null; author_subject: string | null; operator_ai: string | null; }[]; picked: number; set_total: number; };

export type AssetIndexEntryDto = { id: string; persona_id: string; modality: string | null; occurred_at_ms: number; labels: string[]; group_ids: string[]; primary_group_position: number | null; created_at_ms: number; updated_at_ms: number; duration_ms: number | null; file_size_bytes: number | null; pixel_count: number | null; role: string; };

export type AssetIndexPageDto = { items: { id: string; persona_id: string; modality: string | null; occurred_at_ms: number; labels: string[]; group_ids: string[]; primary_group_position: number | null; created_at_ms: number; updated_at_ms: number; duration_ms: number | null; file_size_bytes: number | null; pixel_count: number | null; role: string; }[]; offset: number; limit: number; total: number | null; };

export type AssetDto = { id: string; persona_id: string; source_kind: string; locator: string; file_size_bytes: number | null; platform: string | null; mime: string | null; media: string; content_hash: string | null; modality: string | null; labels: string[]; occurred_at_ms: number; container_id: string | null; title: string | null; bundle_id: string | null; role: string; cover: string | null; keywords: string[]; register_note: string | null; visibility_restricted: boolean; visibility_sharing: string[]; duration_ms: number | null; width_px: number | null; height_px: number | null; rating: number | null; palette: string[] | null; extra_json: string | null; created_at_ms: number; updated_at_ms: number; author_kind: string | null; author_subject: string | null; operator_ai: string | null; attributed_via: string | null; on_duplicate: string | null; folded_into: string | null; fold_policy: string; };

export type TagDto = { id: string; name: string; axis: string | null; };

export type TagCountDto = { tag: { id: string; name: string; axis: string | null; }; asset_count: number; };

export type SessionDto = { id: string; persona_id: string; external_key: string; title: string | null; note: string | null; cover_hint: string | null; started_at_ms: number; ended_at_ms: number; message_count: number; created_at_ms: number; updated_at_ms: number; };

export type SessionPageDto = { items: { id: string; persona_id: string; external_key: string; title: string | null; note: string | null; cover_hint: string | null; started_at_ms: number; ended_at_ms: number; message_count: number; created_at_ms: number; updated_at_ms: number; }[]; total: number | null; offset: number; limit: number; };

export type GroupDto = { id: string; persona_id: string; name: string; description: string | null; dir_id: string | null; kind: string; query_json: string | null; origin_snapshot_id: string | null; last_refresh_at_ms: number | null; last_refresh_status: string | null; last_refresh_error: string | null; created_at_ms: number; updated_at_ms: number; };

export type GroupSummaryDto = { group: { id: string; persona_id: string; name: string; description: string | null; dir_id: string | null; kind: string; query_json: string | null; origin_snapshot_id: string | null; last_refresh_at_ms: number | null; last_refresh_status: string | null; last_refresh_error: string | null; created_at_ms: number; updated_at_ms: number; }; asset_count: number; };

export type DirDto = { id: string; persona_id: string; parent_id: string | null; name: string; position: number; created_at_ms: number; updated_at_ms: number; };

export type GroupLinkDto = { parent_group_id: string; child_group_id: string; position: number; };

export type AssetTextDto = { asset_id: string; text: string | null; };

export type EdgeDto = { id: string; from_asset_id: string; to_asset_id: string; kind: string; label: string | null; weight: number | null; };

export type ConstellationItemDto = { edge: { id: string; from_asset_id: string; to_asset_id: string; kind: string; label: string | null; weight: number | null; }; card: { id: string; persona_id: string; modality: string | null; occurred_at_ms: number; cover: string | null; labels: string[]; file_size_bytes: number | null; duration_ms: number | null; pixel_count: number | null; mime: string | null; media: string; source_locator: string; group_ids: string[]; primary_group_position: number | null; created_at_ms: number; updated_at_ms: number; rating: number | null; palette: string[] | null; has_note: boolean; has_thread: boolean; role: string; title: string | null; member_count: number; score: number | null; snippet: string | null; author_kind: string | null; author_subject: string | null; operator_ai: string | null; }; direction: string; };

export type ProvenanceViewDto = { asset_id: string; ancestors: { id: string; persona_id: string; modality: string | null; occurred_at_ms: number; cover: string | null; labels: string[]; file_size_bytes: number | null; duration_ms: number | null; pixel_count: number | null; mime: string | null; media: string; source_locator: string; group_ids: string[]; primary_group_position: number | null; created_at_ms: number; updated_at_ms: number; rating: number | null; palette: string[] | null; has_note: boolean; has_thread: boolean; role: string; title: string | null; member_count: number; score: number | null; snippet: string | null; author_kind: string | null; author_subject: string | null; operator_ai: string | null; }[]; descendants: { id: string; persona_id: string; modality: string | null; occurred_at_ms: number; cover: string | null; labels: string[]; file_size_bytes: number | null; duration_ms: number | null; pixel_count: number | null; mime: string | null; media: string; source_locator: string; group_ids: string[]; primary_group_position: number | null; created_at_ms: number; updated_at_ms: number; rating: number | null; palette: string[] | null; has_note: boolean; has_thread: boolean; role: string; title: string | null; member_count: number; score: number | null; snippet: string | null; author_kind: string | null; author_subject: string | null; operator_ai: string | null; }[]; };

export type LineageNodeDto = { card: { id: string; persona_id: string; modality: string | null; occurred_at_ms: number; cover: string | null; labels: string[]; file_size_bytes: number | null; duration_ms: number | null; pixel_count: number | null; mime: string | null; media: string; source_locator: string; group_ids: string[]; primary_group_position: number | null; created_at_ms: number; updated_at_ms: number; rating: number | null; palette: string[] | null; has_note: boolean; has_thread: boolean; role: string; title: string | null; member_count: number; score: number | null; snippet: string | null; author_kind: string | null; author_subject: string | null; operator_ai: string | null; }; depth: number; dispatch_id: string | null; };

export type LineageEdgeDto = { from_asset_id: string; to_asset_id: string; label: string | null; };

export type LineageViewDto = { asset_id: string; nodes: { card: { id: string; persona_id: string; modality: string | null; occurred_at_ms: number; cover: string | null; labels: string[]; file_size_bytes: number | null; duration_ms: number | null; pixel_count: number | null; mime: string | null; media: string; source_locator: string; group_ids: string[]; primary_group_position: number | null; created_at_ms: number; updated_at_ms: number; rating: number | null; palette: string[] | null; has_note: boolean; has_thread: boolean; role: string; title: string | null; member_count: number; score: number | null; snippet: string | null; author_kind: string | null; author_subject: string | null; operator_ai: string | null; }; depth: number; dispatch_id: string | null; }[]; edges: { from_asset_id: string; to_asset_id: string; label: string | null; }[]; roots: string[]; dispatch_ids: string[]; truncated: boolean; };

export type AssetDetailDto = { asset: { id: string; persona_id: string; source_kind: string; locator: string; file_size_bytes: number | null; platform: string | null; mime: string | null; media: string; content_hash: string | null; modality: string | null; labels: string[]; occurred_at_ms: number; container_id: string | null; title: string | null; bundle_id: string | null; role: string; cover: string | null; keywords: string[]; register_note: string | null; visibility_restricted: boolean; visibility_sharing: string[]; duration_ms: number | null; width_px: number | null; height_px: number | null; rating: number | null; palette: string[] | null; extra_json: string | null; created_at_ms: number; updated_at_ms: number; author_kind: string | null; author_subject: string | null; operator_ai: string | null; attributed_via: string | null; on_duplicate: string | null; folded_into: string | null; fold_policy: string; }; tags: { id: string; name: string; axis: string | null; }[]; edges: { id: string; from_asset_id: string; to_asset_id: string; kind: string; label: string | null; weight: number | null; }[]; };

export type JobDto = { id: string; kind: string; state: string; progress_current: number; progress_total: number | null; progress_message: string | null; created_at_ms: number; updated_at_ms: number; };

export type JobKindSnapshotDto = { total: number; done: number; pending: number; running: number; failed: number; };

export type JobsSnapshotDto = { total: number; done: number; pending: number; running: number; failed: number; by_kind: Record<string, { total: number; done: number; pending: number; running: number; failed: number; }>; };

export type SnapshotDto = { id: string; persona_id: string; content_hash: string; asset_ids: string[]; created_at_ms: number; };

export type DispatchDto = { id: string; snapshot_id: string; persona_id: string; pursuit_id: string | null; exporter_slug: string; action: string; params_json: string; state: string; state_message: string | null; progress_current: number | null; progress_total: number | null; output_asset_ids: string[]; created_at_ms: number; updated_at_ms: number; completed_at_ms: number | null; source_group_id: string | null; source_query_json: string | null; operator_ai: string | null; };

export type SavedQueryDto = { id: string; persona_id: string; name: string; filter_json: string; sort_json: string; position: number; created_at_ms: number; updated_at_ms: number; };

export type AssetCountEntryDto = { key: string; count: number; };

export type DuplicateAxis = 'artefact' | 'content' | 'meta';

export type DuplicateGroupDto = { axis: 'artefact' | 'content' | 'meta'; content_hash: string; members: { id: string; persona_id: string; modality: string | null; occurred_at_ms: number; cover: string | null; labels: string[]; file_size_bytes: number | null; duration_ms: number | null; pixel_count: number | null; mime: string | null; media: string; source_locator: string; group_ids: string[]; primary_group_position: number | null; created_at_ms: number; updated_at_ms: number; rating: number | null; palette: string[] | null; has_note: boolean; has_thread: boolean; role: string; title: string | null; member_count: number; score: number | null; snippet: string | null; author_kind: string | null; author_subject: string | null; operator_ai: string | null; }[]; };

export type DuplicateReportDto = { groups: { axis: 'artefact' | 'content' | 'meta'; content_hash: string; members: { id: string; persona_id: string; modality: string | null; occurred_at_ms: number; cover: string | null; labels: string[]; file_size_bytes: number | null; duration_ms: number | null; pixel_count: number | null; mime: string | null; media: string; source_locator: string; group_ids: string[]; primary_group_position: number | null; created_at_ms: number; updated_at_ms: number; rating: number | null; palette: string[] | null; has_note: boolean; has_thread: boolean; role: string; title: string | null; member_count: number; score: number | null; snippet: string | null; author_kind: string | null; author_subject: string | null; operator_ai: string | null; }[]; }[]; unhashed_count: number; unwalked_count: number; };

export type DuplicateConflictDto = { id: string; axis: 'artefact' | 'content' | 'meta'; content_hash: string; newcomer: { id: string; persona_id: string; modality: string | null; occurred_at_ms: number; cover: string | null; labels: string[]; file_size_bytes: number | null; duration_ms: number | null; pixel_count: number | null; mime: string | null; media: string; source_locator: string; group_ids: string[]; primary_group_position: number | null; created_at_ms: number; updated_at_ms: number; rating: number | null; palette: string[] | null; has_note: boolean; has_thread: boolean; role: string; title: string | null; member_count: number; score: number | null; snippet: string | null; author_kind: string | null; author_subject: string | null; operator_ai: string | null; }; incumbent: { id: string; persona_id: string; modality: string | null; occurred_at_ms: number; cover: string | null; labels: string[]; file_size_bytes: number | null; duration_ms: number | null; pixel_count: number | null; mime: string | null; media: string; source_locator: string; group_ids: string[]; primary_group_position: number | null; created_at_ms: number; updated_at_ms: number; rating: number | null; palette: string[] | null; has_note: boolean; has_thread: boolean; role: string; title: string | null; member_count: number; score: number | null; snippet: string | null; author_kind: string | null; author_subject: string | null; operator_ai: string | null; }; fold_exclusion: string | null; detected_at_ms: number; };

export type DuplicateResolutionDto = { conflict_id: string; resolution: string; resolved_at_ms: number; keeper_id: string | null; headstone_id: string | null; };

export type MergeAssetsDto = { keeper_id: string; folded_ids: string[]; already_folded_ids: string[]; refusals: { asset_id: string; reason: string; }[]; warnings: { keeper_id: string; headstone_id: string; kind: string; }[]; totals: { edges_repointed: number; edges_dropped: number; buckets_moved: number; children_repointed: number; tags_moved: number; comments_moved: number; threads_reanchored: number; columns_merged: number; values_discarded: number; }; committed: boolean; };

export type MergeRefusalDto = { asset_id: string; reason: string; };

export type MergeWarningDto = { keeper_id: string; headstone_id: string; kind: string; };

export type MergeTotalsDto = { edges_repointed: number; edges_dropped: number; buckets_moved: number; children_repointed: number; tags_moved: number; comments_moved: number; threads_reanchored: number; columns_merged: number; values_discarded: number; };

export type ModalityDefDto = { slug: string; label: string; terminal: boolean; sort_order: number; hidden: boolean; cover_template: string | null; asset_count: number; };

export type SettingLayerDto = { source: string; value_json: string; origin: string | null; rejected: string | null; };

export type SettingDto = { key: string; kind: string; value_json: string; source: string; layers: { source: string; value_json: string; origin: string | null; rejected: string | null; }[]; env_var: string | null; min: number | null; max: number | null; summary: string; };

export type AssetCommentDto = { id: string; asset_id: string; author_kind: string; author_persona_id: string | null; body: string; created_at_ms: number; edited_at_ms: number | null; };

export type MaterialMarkDto = { id: string; asset_id: string; anchor_kind: string; start_ms: number | null; end_ms: number | null; author_kind: string; author_persona_id: string | null; body: string; created_at_ms: number; edited_at_ms: number | null; };

export type MaterialLayerDto = { id: string; asset_id: string; material_ord: number; origin: string; role: string; is_default: boolean; ord: number; };

export type ChapterMarkDto = { id: string; layer_id: string; start_ms: number; end_ms: number | null; label: string; ord: number; };

export type MaterialLayerViewDto = { layer: { id: string; asset_id: string; material_ord: number; origin: string; role: string; is_default: boolean; ord: number; }; chapters: { id: string; layer_id: string; start_ms: number; end_ms: number | null; label: string; ord: number; }[]; };

export type EventDto = { id: string; kind: string; occurred_at_ms: number; persona_id: string | null; duration_ms: number | null; payload_json: string | null; };

export type VideoPreviewDto = { status: string; path: string | null; detail: string | null; };

export type CreateThreadCommand = { anchor_kind: string; anchor_id: string | null; title: string; };

export type ArchiveThreadCommand = { thread_id: string; archived: boolean; };

export type DeleteThreadCommand = { thread_id: string; };

export type AppendMessageCommand = { thread_id: string; author_kind: string; author_name: string | null; author_persona_id: string | null; role: string; body: string; refs: { kind: string; id: string; }[]; idempotency_key: string | null; };

export type DeleteMessageCommand = { message_id: string; };

export type ThreadDto = { id: string; title: string; anchor: { kind: string; id: string | null; }; created_at_ms: number; updated_at_ms: number; last_message_at_ms: number | null; message_count: number; archived: boolean; };

export type ThreadAnchorDto = { kind: string; id: string | null; };

export type MessageDto = { id: string; thread_id: string; author_kind: string; author_name: string | null; author_persona_id: string | null; role: string; body: string; refs: { kind: string; id: string; }[]; created_at_ms: number; };

export type MessageRefDto = { kind: string; id: string; };

export type OpenPursuitCommand = { persona_id: string; pursuit_id: string | null; parent_pursuit_id: string | null; title: string | null; note: string | null; operator_ai: string | null; };

export type ClosePursuitCommand = { pursuit_id: string; outcome: string; verdicts: { asset_id: string; verdict: string; note: string | null; }[]; note: string | null; cull_note: string | null; operator_ai: string | null; };

export type CullVerdictEntry = { asset_id: string; verdict: string; note: string | null; };

export type RecordPursuitTxCommand = { pursuit_id: string; kind: string; asset_id: string; origin: string | null; note: string | null; operator_ai: string | null; };

export type ReopenPursuitCommand = { pursuit_id: string; note: string | null; operator_ai: string | null; };

export type RestampDispatchCommand = { dispatch_id: string; to_pursuit_id: string; operator_ai: string | null; };

export type PursuitDto = { id: string; persona_id: string; parent_id: string | null; title: string | null; note: string | null; standing: string; created_at_ms: number; };

export type PursuitEventDto = { id: string; pursuit_id: string; kind: string; snapshot_id: string | null; note: string | null; created_at_ms: number; };

export type PursuitViewDto = { pursuit: { id: string; persona_id: string; parent_id: string | null; title: string | null; note: string | null; standing: string; created_at_ms: number; }; rounds: { id: string; snapshot_id: string; persona_id: string; pursuit_id: string | null; exporter_slug: string; action: string; params_json: string; state: string; state_message: string | null; progress_current: number | null; progress_total: number | null; output_asset_ids: string[]; created_at_ms: number; updated_at_ms: number; completed_at_ms: number | null; source_group_id: string | null; source_query_json: string | null; operator_ai: string | null; }[]; returns: string[]; events: { id: string; pursuit_id: string; kind: string; snapshot_id: string | null; note: string | null; created_at_ms: number; }[]; txs: { id: string; pursuit_id: string; kind: string; origin: string | null; asset_id: string; note: string | null; author_kind: string | null; operator_ai: string | null; created_at_ms: number; }[]; culls: { id: string; pursuit_id: string; pursuit_event_id: string; candidate_snapshot_id: string; note: string | null; author_kind: string | null; operator_ai: string | null; created_at_ms: number; members: { asset_id: string; verdict: string; note: string | null; }[]; }[]; };

export type PursuitTxDto = { id: string; pursuit_id: string; kind: string; origin: string | null; asset_id: string; note: string | null; author_kind: string | null; operator_ai: string | null; created_at_ms: number; };

export type CullDto = { id: string; pursuit_id: string; pursuit_event_id: string; candidate_snapshot_id: string; note: string | null; author_kind: string | null; operator_ai: string | null; created_at_ms: number; members: { asset_id: string; verdict: string; note: string | null; }[]; };

export type CullMemberDto = { asset_id: string; verdict: string; note: string | null; };

export type AssetCullDto = { cull_id: string; pursuit_id: string; candidate_snapshot_id: string; verdict: string; note: string | null; author_kind: string | null; operator_ai: string | null; created_at_ms: number; };

