#!/usr/bin/env python3
"""Holds THIRD-PARTY-NOTICES.md and scripts/copyleft-sources.txt to the tree.

The notice is generated by `just licences`, which needs `cargo-about`. This
check needs nothing but `cargo metadata`, which is what lets it run on every
branch.

**It evaluates no licence expressions, deliberately.** An earlier version of
this file did, and got it wrong twice in ways nothing noticed: it matched
copyleft families by string prefix, where `"LGPL-2.1-or-later"` does not start
with `"GPL-"` and neither does `"AGPL-3.0-only"`, so the two families this
repository has already had to answer for would have passed; and it read an
`OR` and an `AND` the same way, so `(MIT OR Apache-2.0) AND MPL-2.0` came back
as no obligation at all. Both were second implementations of something
`cargo-about` already does with a real SPDX evaluator, and the second
implementation was the wrong one.

So the policy lives in `about.toml`'s accepted list and is enforced by the
generator: a package whose licence is not on that list fails `just licences`,
which is why `LGPL-2.1-or-later`, GPL and AGPL are absent from it. What this
script does is read the generator's output and hold two things to it:

- **Nothing the notice names has left the lockfile.** This is what a
  dependency bump leaves behind, and it is the ordinary way the file goes
  stale.
- **The crates under an obliging licence are exactly the ones
  `scripts/copyleft-sources.txt` records**, in both directions. A release
  attaches source for what that file names; a package that obliges source and
  is not on it would ship with an obligation nobody answered, and a line for a
  package that has gone would have the release offering source for something
  it does not ship.

`OBLIGING` is small on purpose. It does not need to enumerate copyleft — it
needs to name the licences that both oblige a source offer *and* appear in
`about.toml`'s accepted list, because nothing else can reach the notice.

**What it does not catch.** A newly added *permissive* dependency missing from
the notice. Knowing which packages the notice should contain means resolving
the graph for one target, which is the generator's job. The release workflow
regenerates the notice with the real tool and fails on any difference, which
is where that answer belongs: it is the run that ships the file.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTICE = ROOT / "THIRD-PARTY-NOTICES.md"
COPYLEFT = ROOT / "scripts" / "copyleft-sources.txt"

# The section headings and entries the template writes.
HEADING = re.compile(r"^## (.+)$")
ENTRY = re.compile(r"^- \[([A-Za-z0-9_.-]+) ([^\]]+)\]\(")

# Licence sections whose packages owe more than attribution, named as
# `cargo-about` titles them. Only a licence on `about.toml`'s accepted list
# can appear in the notice at all, so this set is the intersection of "asks
# for source" with "this repository decided to accept it" — one entry today.
OBLIGING = {"Mozilla Public License 2.0"}


def metadata() -> dict:
    result = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--offline", "--locked",
         "--manifest-path", str(ROOT / "Cargo.toml")],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        sys.exit(
            "cargo metadata --locked --offline failed, so nothing here can "
            "answer for the notice:\n" + result.stderr.strip()
        )
    return json.loads(result.stdout)


def sections() -> list[tuple[str, set[tuple[str, str]]]]:
    """(licence title, {(name, version)}) for each section of the notice.

    Pairs rather than names: one crate can appear at two versions in a graph
    this size, and one crate can appear under two licences when its expression
    is an `AND`.
    """
    out: list[tuple[str, set[tuple[str, str]]]] = []
    title, crates = None, set()
    for line in NOTICE.read_text().splitlines():
        heading = HEADING.match(line)
        if heading:
            if title is not None:
                out.append((title, crates))
            title, crates = heading.group(1).strip(), set()
            continue
        entry = ENTRY.match(line)
        if entry and title is not None:
            crates.add((entry.group(1), entry.group(2)))
    if title is not None:
        out.append((title, crates))
    if not out:
        sys.exit(
            f"{NOTICE.name} has no licence sections — regenerate it with "
            f"`just licences`"
        )
    return out


def recorded() -> set[str]:
    return {
        line.split("#", 1)[0].strip()
        for line in COPYLEFT.read_text().splitlines()
        if line.split("#", 1)[0].strip()
    }


def main() -> int:
    meta = metadata()
    in_lock = {(p["name"], p["version"]) for p in meta["packages"]}
    failures: list[str] = []

    parsed = sections()
    named = {pair for _, crates in parsed for pair in crates}
    for name, version in sorted(named):
        if (name, version) not in in_lock:
            at = sorted(v for n, v in in_lock if n == name)
            moved = f"the lockfile has {', '.join(at)}" if at else "it is gone"
            failures.append(
                f"{NOTICE.name} names {name} {version} and {moved} — the "
                f"notice is stale, regenerate it with `just licences`"
            )

    obliging = {
        name
        for title, crates in parsed
        if title in OBLIGING
        for name, _ in crates
    }
    listed = recorded()

    for name in sorted(obliging - listed):
        failures.append(
            f"{NOTICE.name} lists {name} under a licence that asks for source "
            f"as well as attribution, and no line in "
            f"{COPYLEFT.relative_to(ROOT)} names it — the release attaches "
            f"what that file lists, so add it there in this change"
        )
    for name in sorted(listed - obliging):
        failures.append(
            f"{COPYLEFT.relative_to(ROOT)} names {name} and {NOTICE.name} "
            f"lists it under no licence that asks for source — the release "
            f"would offer source for something it does not owe"
        )

    if failures:
        print("\n".join(failures), file=sys.stderr)
        return 1
    print(
        f"third-party notices: {len(named)} package(s) named, all present in "
        f"the lockfile; {len(obliging)} owing source, all recorded"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
