#!/usr/bin/env python3
"""Holds THIRD-PARTY-NOTICES.md and scripts/copyleft-sources.txt to the tree.

The notice is generated by `just licences`, which needs `cargo-about`. This
check needs nothing but `cargo metadata`, which is why it can sit in
`check-shared` and run on every branch. What it buys and what it does not is
worth stating plainly, because the difference is the reason the release
workflow regenerates the file rather than trusting this.

**What it catches.** Two things, and they are the two that carry an
obligation:

- A package named in the notice that is no longer in `Cargo.lock` at that
  version. This is what a dependency bump leaves behind, and it is the
  ordinary way the file goes stale.
- A copyleft package in the dependency graph that the notice does not name,
  or that is not on `scripts/copyleft-sources.txt`. A new MPL dependency
  arrives with a source-availability obligation attached (MPL-2.0 §3.2), and
  arriving unnoticed is the failure worth spending a gate on. The list is
  held in both directions, so a line for a package that has gone is a failure
  too — a release would otherwise keep offering source for something it no
  longer ships.

**What it does not catch.** A newly added *permissive* dependency missing
from the notice. Catching that needs the set of packages the notice should
contain, and `cargo-about` computes it with a target filter — this notice
describes `aarch64-apple-darwin` — which means evaluating the `cfg`
expressions on every dependency edge. Reimplementing that here to check a
tool's arithmetic would be the second implementation of it in this
repository, and the wrong one. The release workflow regenerates the notice
with the real tool and fails on any difference, which is where that answer
belongs: it is the run that ships the file.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTICE = ROOT / "THIRD-PARTY-NOTICES.md"
COPYLEFT = ROOT / "scripts" / "copyleft-sources.txt"

# Every entry the template writes: `- [name version](url)`.
ENTRY = re.compile(r"^- \[([A-Za-z0-9_.-]+) ([^\]]+)\]\(")

# Families that oblige more than attribution. A package whose expression names
# one of these *and* offers no permissive alternative is one this repository
# has to answer for; `about.toml`'s accepted list is what decides which of an
# `OR` it takes, and the two are checked against each other here.
COPYLEFT_FAMILIES = ("MPL-", "GPL-", "EPL-", "CDDL-", "OSL-", "SSPL-", "CPAL-")
PERMISSIVE = {
    "MIT", "MIT-0", "Apache-2.0", "0BSD", "BSD-1-Clause", "BSD-2-Clause",
    "BSD-3-Clause", "BSL-1.0", "CC0-1.0", "CDLA-Permissive-2.0", "ISC",
    "NCSA", "Unicode-3.0", "Unlicense", "Zlib", "zlib-acknowledgement",
}


def metadata() -> dict:
    result = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--offline", "--locked",
         "--manifest-path", str(ROOT / "Cargo.toml")],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        sys.exit(
            "cargo metadata --locked --offline failed, so nothing here can "
            "answer for the notice:\n" + result.stderr.strip()
        )
    return json.loads(result.stdout)


def atoms(expression: str) -> set[str]:
    """The SPDX identifiers an expression names, ignoring its structure."""
    return {
        a.strip()
        for a in re.split(r"[()]|\s+(?:OR|AND|WITH)\s+|/", expression)
        if a.strip()
    }


def obliged(expression: str | None) -> bool:
    """True when every way of taking this licence carries a copyleft term."""
    if not expression:
        return False
    found = atoms(expression)
    if not any(a.startswith(COPYLEFT_FAMILIES) for a in found):
        return False
    # An expression offering a permissive alternative is a choice, and
    # `about.toml` takes the permissive side of it.
    return not (found & PERMISSIVE)


def listed() -> set[tuple[str, str]]:
    """(name, version) pairs, as the notice names them.

    Pairs rather than a mapping: one crate can appear at two versions in a
    graph this size, and keying by name alone would check one of them and
    silently drop the other.
    """
    out = {
        (m.group(1), m.group(2))
        for m in (ENTRY.match(line) for line in NOTICE.read_text().splitlines())
        if m
    }
    if not out:
        sys.exit(f"{NOTICE.name} names no packages — regenerate it with `just licences`")
    return out


def main() -> int:
    meta = metadata()
    packages = {p["id"]: p for p in meta["packages"]}
    members = set(meta["workspace_members"])
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}

    # Everything the app could link, over-approximated: every dependency kind
    # but dev, every target. A superset is the safe side for the question
    # asked here, which is whether something obliging is present at all.
    ui = next(i for i in members if packages[i]["name"] == "asterism-ui")
    reachable, queue = {ui}, [ui]
    while queue:
        for dep in nodes[queue.pop()]["deps"]:
            kinds = {k.get("kind") for k in dep["dep_kinds"]}
            if kinds - {"dev"} and dep["pkg"] not in reachable:
                reachable.add(dep["pkg"])
                queue.append(dep["pkg"])

    in_lock = {(packages[i]["name"], packages[i]["version"]) for i in reachable}
    names_in_lock = {n for n, _ in in_lock}
    failures: list[str] = []

    notice = listed()
    notice_names = {n for n, _ in notice}
    for name, version in sorted(notice):
        if (name, version) not in in_lock:
            at = [v for n, v in in_lock if n == name]
            moved = f"the lockfile has {', '.join(sorted(at))}" if at else "it is gone"
            failures.append(
                f"{NOTICE.name} names {name} {version} and {moved} — the "
                f"notice is stale, regenerate it with `just licences`"
            )

    obliging = {
        packages[i]["name"]
        for i in reachable
        if i not in members and obliged(packages[i].get("license"))
    }
    recorded = {
        line.split("#", 1)[0].strip()
        for line in COPYLEFT.read_text().splitlines()
        if line.split("#", 1)[0].strip()
    }

    for name in sorted(obliging - recorded):
        failures.append(
            f"{name} is licensed {packages[next(i for i in reachable if packages[i]['name'] == name)].get('license')} "
            f"with no permissive alternative, and no line in "
            f"{COPYLEFT.relative_to(ROOT)} names it. Its source has to be "
            f"offered with the release; add it there in this change"
        )
    for name in sorted(recorded - obliging):
        where = "is no longer a dependency" if name not in names_in_lock else "no longer obliges anything"
        failures.append(
            f"{COPYLEFT.relative_to(ROOT)} names {name} and it {where} — "
            f"the release would offer source for something it does not ship"
        )
    for name in sorted(obliging & recorded):
        if name not in notice_names:
            failures.append(
                f"{name} obliges a source offer and {NOTICE.name} does not "
                f"name it — regenerate with `just licences`"
            )

    if failures:
        print("\n".join(failures), file=sys.stderr)
        return 1
    print(
        f"third-party notices: {len(notice)} package(s) named, all present in "
        f"the lockfile; {len(obliging)} obliging source, all recorded"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
