//! The manifest: what a corpus *is*, and what a given run realised.
//!
//! A bench number without a corpus identity is not comparable to anything.
//! `(seed, generator_version, preset)` is that identity, and every recorded
//! measurement (perf-baseline, `GET /asterism/perf`) is expected to carry it
//! alongside the number — comparing two runs generated from different seeds
//! is the failure this file exists to make visible.
//!
//! The rest of the fields are *realised* values, not parameters: the model
//! declares intent (7 % rated, one 10,000-capacity group), the manifest
//! records what the finite prefix actually produced. Reading the two side by
//! side is how a distribution regression gets noticed.
//!
//! The manifest is also the idempotency key: a rerun whose
//! `(seed, generator_version, preset)` matches an existing manifest of at
//! least the requested count has nothing to do.
//!
//! `generated_at_ms` is the only wall-clock value in this crate. Nothing
//! reads it back — it exists for humans reading the file — and it must not
//! leak into any generation path (see [`crate::model`]).

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::time::{SystemTime, UNIX_EPOCH};

use crate::model::{AssetSpec, PERSONA_COUNT};

pub const MANIFEST_SCHEMA: &str = "benchgen-manifest-v1";
/// Bumped whenever a change would alter generated bytes or the spec stream.
/// Part of the idempotency key, so a bump forces regeneration rather than
/// silently mixing two generations in one corpus directory.
pub const GENERATOR_VERSION: &str = "0.2.0";

/// Encoded-size buckets, in MB: `<0.5 / 0.5–0.8 / 0.8–1.2 / 1.2–1.6 /
/// 1.6–2.0 / >2.0`. The middle three are the reference band.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct SizeHistogram {
    pub lt_0_5mb: u64,
    pub mb_0_5_to_0_8: u64,
    pub mb_0_8_to_1_2: u64,
    pub mb_1_2_to_1_6: u64,
    pub mb_1_6_to_2_0: u64,
    pub gt_2_0mb: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Manifest {
    pub schema: String,
    pub seed: u64,
    pub generator_version: String,
    pub preset: String,
    pub count: u64,
    /// `None` for the metadata-only tier, which writes no files. Omitted
    /// from the JSON rather than written as `null`, so it must default on
    /// the way back in — an existing manifest is read to decide whether a
    /// rerun can be skipped.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size_histogram: Option<SizeHistogram>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size_total_bytes: Option<u64>,
    /// Recorded because the reference workload is stated as a median file
    /// size; comparing import throughput without it means comparing two
    /// different workloads.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size_median_bytes: Option<u64>,
    pub persona_counts: Vec<u64>,
    pub tag_total: u64,
    pub label_total: u64,
    pub group_realized: BTreeMap<String, u64>,
    pub rated_count: u64,
    pub trashed_count: u64,
    pub occurred_at_min_ms: i64,
    pub occurred_at_max_ms: i64,
    pub generated_at_ms: i64,
    pub elapsed_ms: u64,
}

impl Manifest {
    /// Whether an existing manifest can stand in for the requested run.
    pub fn covers(&self, seed: u64, preset: &str, count: u64) -> bool {
        self.schema == MANIFEST_SCHEMA
            && self.seed == seed
            && self.generator_version == GENERATOR_VERSION
            && self.preset == preset
            && self.count >= count
    }

    /// Group names ordered by realised membership, largest first — the shape
    /// a bench driver picks scroll targets from.
    pub fn top_groups(&self, n: usize) -> Vec<(String, u64)> {
        let mut rows: Vec<(String, u64)> = self
            .group_realized
            .iter()
            .map(|(k, v)| (k.clone(), *v))
            .collect();
        rows.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(&b.0)));
        rows.truncate(n);
        rows
    }
}

/// Accumulates realised values while a corpus is generated.
///
/// Sizes are kept individually so the median is exact; at the largest preset
/// that writes files (12,000) it is a few hundred KB of `u64`, and the
/// metadata-only tier records no sizes at all.
pub struct ManifestBuilder {
    seed: u64,
    preset: String,
    persona_counts: Vec<u64>,
    tag_total: u64,
    label_total: u64,
    group_realized: BTreeMap<String, u64>,
    rated_count: u64,
    trashed_count: u64,
    occurred_at_min_ms: i64,
    occurred_at_max_ms: i64,
    count: u64,
    sizes: Vec<u64>,
}

impl ManifestBuilder {
    pub fn new(seed: u64, preset: &str) -> Self {
        Self {
            seed,
            preset: preset.to_string(),
            persona_counts: vec![0; PERSONA_COUNT],
            tag_total: 0,
            label_total: 0,
            group_realized: BTreeMap::new(),
            rated_count: 0,
            trashed_count: 0,
            occurred_at_min_ms: i64::MAX,
            occurred_at_max_ms: i64::MIN,
            count: 0,
            sizes: Vec::new(),
        }
    }

    /// Fold one asset in. `encoded_bytes` is `None` for the metadata-only
    /// tier; a skipped-but-present file passes its on-disk length, so a
    /// resumed run reports the same histogram as an uninterrupted one.
    pub fn observe(&mut self, spec: &AssetSpec, encoded_bytes: Option<u64>) {
        self.count += 1;
        if let Some(slot) = self.persona_counts.get_mut(spec.persona_idx) {
            *slot += 1;
        }
        self.tag_total += spec.tags.len() as u64;
        self.label_total += spec.labels.len() as u64;
        for group in &spec.groups {
            *self.group_realized.entry(group.clone()).or_default() += 1;
        }
        if spec.rating.is_some() {
            self.rated_count += 1;
        }
        if spec.trashed {
            self.trashed_count += 1;
        }
        self.occurred_at_min_ms = self.occurred_at_min_ms.min(spec.occurred_at_ms);
        self.occurred_at_max_ms = self.occurred_at_max_ms.max(spec.occurred_at_ms);
        if let Some(bytes) = encoded_bytes {
            self.sizes.push(bytes);
        }
    }

    pub fn count(&self) -> u64 {
        self.count
    }

    pub fn finish(mut self, elapsed_ms: u64) -> Manifest {
        let (histogram, total, median) = if self.sizes.is_empty() {
            (None, None, None)
        } else {
            self.sizes.sort_unstable();
            let mut hist = SizeHistogram::default();
            for bytes in &self.sizes {
                let mb = *bytes as f64 / 1_000_000.0;
                match mb {
                    m if m < 0.5 => hist.lt_0_5mb += 1,
                    m if m < 0.8 => hist.mb_0_5_to_0_8 += 1,
                    m if m < 1.2 => hist.mb_0_8_to_1_2 += 1,
                    m if m < 1.6 => hist.mb_1_2_to_1_6 += 1,
                    m if m <= 2.0 => hist.mb_1_6_to_2_0 += 1,
                    _ => hist.gt_2_0mb += 1,
                }
            }
            let total: u64 = self.sizes.iter().sum();
            let median = self.sizes[self.sizes.len() / 2];
            (Some(hist), Some(total), Some(median))
        };

        Manifest {
            schema: MANIFEST_SCHEMA.to_string(),
            seed: self.seed,
            generator_version: GENERATOR_VERSION.to_string(),
            preset: self.preset,
            count: self.count,
            size_histogram: histogram,
            size_total_bytes: total,
            size_median_bytes: median,
            persona_counts: self.persona_counts,
            tag_total: self.tag_total,
            label_total: self.label_total,
            group_realized: self.group_realized,
            rated_count: self.rated_count,
            trashed_count: self.trashed_count,
            occurred_at_min_ms: if self.count == 0 {
                0
            } else {
                self.occurred_at_min_ms
            },
            occurred_at_max_ms: if self.count == 0 {
                0
            } else {
                self.occurred_at_max_ms
            },
            generated_at_ms: now_ms(),
            elapsed_ms,
        }
    }
}

pub(crate) fn now_ms() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::SpecStream;

    fn built(preset: &str, with_sizes: bool) -> Manifest {
        let mut builder = ManifestBuilder::new(42, preset);
        for (i, spec) in SpecStream::new(42).take(500).enumerate() {
            let bytes = with_sizes.then(|| 700_000 + (i as u64 % 5) * 400_000);
            builder.observe(&spec, bytes);
        }
        builder.finish(1_234)
    }

    #[test]
    fn aggregates_match_the_specs_folded_in() {
        let m = built("s", true);
        assert_eq!(m.count, 500);
        assert_eq!(m.persona_counts.iter().sum::<u64>(), 500);
        assert_eq!(m.schema, MANIFEST_SCHEMA);
        assert!(m.tag_total > 0 && m.label_total > 0);
        assert!(m.group_realized.values().sum::<u64>() > 0);

        let hist = m.size_histogram.expect("sizes were provided");
        let total: u64 = hist.lt_0_5mb
            + hist.mb_0_5_to_0_8
            + hist.mb_0_8_to_1_2
            + hist.mb_1_2_to_1_6
            + hist.mb_1_6_to_2_0
            + hist.gt_2_0mb;
        assert_eq!(total, 500, "every size must land in exactly one bucket");
        assert_eq!(m.size_median_bytes, Some(1_500_000));
    }

    #[test]
    fn metadata_only_tier_reports_no_sizes() {
        let m = built("l", false);
        assert!(m.size_histogram.is_none());
        assert!(m.size_total_bytes.is_none());
        assert!(m.size_median_bytes.is_none());
    }

    #[test]
    fn covers_is_the_idempotency_key() {
        let m = built("s", true);
        assert!(m.covers(42, "s", 500));
        assert!(
            m.covers(42, "s", 200),
            "a longer corpus covers a shorter ask"
        );
        assert!(!m.covers(42, "s", 501));
        assert!(
            !m.covers(43, "s", 500),
            "a different seed is a different corpus"
        );
        assert!(!m.covers(42, "m", 500));
    }

    #[test]
    fn round_trips_through_json() {
        let m = built("s", true);
        let text = serde_json::to_string_pretty(&m).expect("serialize");
        let back: Manifest = serde_json::from_str(&text).expect("deserialize");
        assert_eq!(m, back);
    }

    #[test]
    fn top_groups_is_ordered_by_membership() {
        let m = built("s", true);
        let top = m.top_groups(3);
        assert!(!top.is_empty());
        assert!(top.windows(2).all(|w| w[0].1 >= w[1].1));
        assert_eq!(top[0].0, "bench-mega");
    }
}
