//! The visual-retrieval corpus (#112): known relationships, generated here.
//!
//! `PUBLIC_DEVELOPMENT.md` rules personal library images out of the
//! repository and out of any published benchmark, so the corpus that grades
//! visual retrieval is generated the same way the bench corpus is: from a
//! seed, reproducibly, with the ground truth recorded in a manifest instead
//! of annotated by hand. Every relationship the pipeline is supposed to
//! find — and the ones it is supposed to *refuse* — exists here on purpose:
//!
//! - **exact copy**: byte-identical file under a second name;
//! - **resize / recompress / crop**: ordinary transforms of the base, the
//!   near-duplicate questions a perceptual hash must answer;
//! - **look-alike**: the same scene re-drawn with jittered geometry — no
//!   shared bytes, visually similar, an encoder question rather than a
//!   hash question;
//! - **semantic sibling**: the same describable content (identical tag
//!   set) re-composed from scratch on a different background — related in
//!   meaning, not in looks;
//! - **hard negative**: same background family, different shapes — close
//!   enough in histogram terms to punish a lazy similarity score;
//! - **captions**: an EN and a JA sentence derived from the scene spec, the
//!   text-pairing half (#32 bridge) of the evaluation;
//! - **unrelated queries and images**: strings and noise canvases with no
//!   counterpart, which the honest-failure acceptance test requires to
//!   return nothing.
//!
//! This stream is deliberately separate from [`crate::model::SpecStream`]
//! and its manifest from [`crate::manifest`]: the bench corpus identity
//! `(seed, generator_version, preset)` must not move when this corpus
//! evolves, so the two carry independent schema and version constants.

use anyhow::{Context, Result};
use rand::{Rng, SeedableRng};
use rand_chacha::ChaCha20Rng;
use rayon::prelude::*;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};
use std::time::Instant;

use crate::manifest::now_ms;
use crate::visual_scene::{
    PALETTE, PaletteColor, SHAPES, SceneSpec, ShapeSpec, crop_center, noise_image, render, resize,
    to_jpeg, to_png,
};

pub const VISUAL_MANIFEST_SCHEMA: &str = "benchgen-visual-manifest-v1";
/// Bumped whenever generated bytes or the spec stream would change; part of
/// the idempotency key, independent of the bench tier's version.
pub const VISUAL_GENERATOR_VERSION: &str = "0.1.0";

/// Canvas mix — modest sizes; retrieval cost is not under measurement here.
const DIMS: [(u32, u32); 3] = [(640, 640), (512, 768), (768, 512)];
const SHAPE_COUNT: (usize, usize) = (1, 3);
/// Shapes are placed one per cell of a 2×2 grid, so no shape can occlude
/// another — a tag the spec asserts must be visible in the pixels, or the
/// tag-suggestion ground truth is quietly wrong. Cell distance (0.36),
/// jitter and size are chosen together so even worst-case neighbours do
/// not touch, and everything stays inside the 80 % center crop.
const CELLS: [(f64, f64); 4] = [(0.32, 0.32), (0.68, 0.32), (0.32, 0.68), (0.68, 0.68)];
const CELL_JITTER: f64 = 0.02;
/// Clamp bounds for look-alike jitter; also the widest any center may sit.
const PLACEMENT: (f64, f64) = (0.24, 0.76);
const SHAPE_SIZE: (f64, f64) = (0.08, 0.12);
const RESIZE_FACTOR: f64 = 0.5;
const JPEG_QUALITY: u8 = 75;
const CROP_FRAC: f64 = 0.8;
/// Look-alike geometry jitter: positions move a little, the scene stays
/// recognisably the same picture. Small enough that jittered neighbours
/// still cannot touch (see the non-overlap test).
const JITTER_POS: f64 = 0.03;
const JITTER_SIZE: (f64, f64) = (0.9, 1.1);
const JITTER_ANGLE_DEG: f64 = 20.0;
/// Noise canvases with no counterpart in the corpus, for the
/// honest-failure half of the acceptance test.
const UNRELATED_IMAGES: u64 = 3;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VisualRole {
    Base,
    ExactCopy,
    Resize,
    Recompress,
    Crop,
    Lookalike,
    SemanticSibling,
    HardNegative,
    Unrelated,
}

/// One corpus file and everything that is true about it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct VisualItem {
    pub id: String,
    pub rel_path: String,
    pub role: VisualRole,
    /// The base this file relates to; `None` on bases themselves.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_id: Option<String>,
    pub tags_en: Vec<String>,
    pub tags_ja: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub caption_en_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub caption_ja_path: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct VisualManifest {
    pub schema: String,
    pub seed: u64,
    pub generator_version: String,
    pub bases: u64,
    pub item_count: u64,
    pub items: Vec<VisualItem>,
    /// Queries with no counterpart in the corpus: retrieval is allowed —
    /// required — to return nothing for these.
    pub unrelated_queries_en: Vec<String>,
    pub unrelated_queries_ja: Vec<String>,
    pub generated_at_ms: i64,
    pub elapsed_ms: u64,
}

impl VisualManifest {
    pub fn covers(&self, seed: u64, bases: u64) -> bool {
        self.schema == VISUAL_MANIFEST_SCHEMA
            && self.seed == seed
            && self.generator_version == VISUAL_GENERATOR_VERSION
            && self.bases >= bases
    }
}

fn unrelated_queries_en() -> Vec<String> {
    [
        "a photograph of a cat",
        "city skyline at night",
        "handwritten text on paper",
    ]
    .map(String::from)
    .to_vec()
}

fn unrelated_queries_ja() -> Vec<String> {
    ["猫の写真", "夜の街並み", "紙に書かれた手書きの文字"]
        .map(String::from)
        .to_vec()
}

/// One base scene and its spec-level relatives. Transform variants are
/// file-level and derived at generation time, not here.
#[derive(Debug, Clone, PartialEq)]
pub struct VisualBaseSpec {
    pub index: u64,
    pub scene: SceneSpec,
    /// Every second base has a look-alike.
    pub lookalike: Option<SceneSpec>,
    /// Every third base has a semantic sibling.
    pub semantic_sibling: Option<SceneSpec>,
    /// Every fourth base has a hard negative.
    pub hard_negative: Option<SceneSpec>,
}

impl VisualBaseSpec {
    pub fn id(&self) -> String {
        format!("b{:04}", self.index)
    }
}

/// Seeded, infinite, deterministic — the visual counterpart of
/// [`crate::model::SpecStream`], with the same contract: no wall-clock, no
/// environment, a fixed draw order, and asset `i` reachable only by walking
/// to it.
pub struct VisualStream {
    rng: ChaCha20Rng,
    next_index: u64,
}

impl VisualStream {
    pub fn new(seed: u64) -> Self {
        // Derived seed: this stream must not mirror the bench stream even
        // when both are launched with the same corpus seed.
        Self {
            rng: ChaCha20Rng::seed_from_u64(seed ^ 0xB15C_0DE0_0000_0001),
            next_index: 0,
        }
    }

    fn draw_scene(&mut self) -> SceneSpec {
        let (width, height) = DIMS[self.rng.random_range(0..DIMS.len())];
        let bg0 = PALETTE[self.rng.random_range(0..PALETTE.len())];
        let bg1 = loop {
            let c = PALETTE[self.rng.random_range(0..PALETTE.len())];
            if c != bg0 {
                break c;
            }
        };
        let angle_deg = self.rng.random_range(0.0..360.0);
        let shapes = self.draw_shapes(None);
        SceneSpec {
            width,
            height,
            bg: [bg0, bg1],
            angle_deg,
            shapes,
        }
    }

    /// Draw 1–3 shapes, each in its own grid cell.
    fn draw_shapes(&mut self, exclude: Option<&[PaletteColor]>) -> Vec<ShapeSpec> {
        let count = self.rng.random_range(SHAPE_COUNT.0..=SHAPE_COUNT.1);
        let mut cells = CELLS;
        // Fisher–Yates over the four cells, then take the first `count`.
        for i in (1..cells.len()).rev() {
            let j = self.rng.random_range(0..=i);
            cells.swap(i, j);
        }
        (0..count)
            .map(|i| self.draw_shape_in(cells[i], exclude))
            .collect()
    }

    fn draw_shape_in(&mut self, cell: (f64, f64), exclude: Option<&[PaletteColor]>) -> ShapeSpec {
        let color = loop {
            let c = PALETTE[self.rng.random_range(0..PALETTE.len())];
            if exclude.is_none_or(|banned| !banned.contains(&c)) {
                break c;
            }
        };
        ShapeSpec {
            kind: SHAPES[self.rng.random_range(0..SHAPES.len())],
            color,
            cx: cell.0 + self.rng.random_range(-CELL_JITTER..CELL_JITTER),
            cy: cell.1 + self.rng.random_range(-CELL_JITTER..CELL_JITTER),
            size: self.rng.random_range(SHAPE_SIZE.0..SHAPE_SIZE.1),
        }
    }

    /// Same shapes and colors, jittered geometry: related, not derived.
    fn draw_lookalike(&mut self, base: &SceneSpec) -> SceneSpec {
        let mut alike = base.clone();
        alike.angle_deg = (alike.angle_deg
            + self.rng.random_range(-JITTER_ANGLE_DEG..JITTER_ANGLE_DEG))
        .rem_euclid(360.0);
        for shape in &mut alike.shapes {
            shape.cx = (shape.cx + self.rng.random_range(-JITTER_POS..JITTER_POS))
                .clamp(PLACEMENT.0, PLACEMENT.1);
            shape.cy = (shape.cy + self.rng.random_range(-JITTER_POS..JITTER_POS))
                .clamp(PLACEMENT.0, PLACEMENT.1);
            shape.size = (shape.size * self.rng.random_range(JITTER_SIZE.0..JITTER_SIZE.1))
                .clamp(SHAPE_SIZE.0, SHAPE_SIZE.1);
        }
        alike
    }

    /// Same describable content, different composition: the base's shape
    /// kinds and colors reappear — so the tag set is identical — but the
    /// geometry is drawn from scratch and the background changes. Related
    /// in meaning, not in looks.
    fn draw_semantic_sibling(&mut self, base: &SceneSpec) -> SceneSpec {
        let mut cells = CELLS;
        for i in (1..cells.len()).rev() {
            let j = self.rng.random_range(0..=i);
            cells.swap(i, j);
        }
        let shapes = base
            .shapes
            .iter()
            .zip(cells)
            .map(|(shape, cell)| ShapeSpec {
                kind: shape.kind,
                color: shape.color,
                cx: cell.0 + self.rng.random_range(-CELL_JITTER..CELL_JITTER),
                cy: cell.1 + self.rng.random_range(-CELL_JITTER..CELL_JITTER),
                size: self.rng.random_range(SHAPE_SIZE.0..SHAPE_SIZE.1),
            })
            .collect();
        let bg0 = loop {
            let c = PALETTE[self.rng.random_range(0..PALETTE.len())];
            if !base.bg.contains(&c) {
                break c;
            }
        };
        let bg1 = loop {
            let c = PALETTE[self.rng.random_range(0..PALETTE.len())];
            if c != bg0 && !base.bg.contains(&c) {
                break c;
            }
        };
        SceneSpec {
            width: base.width,
            height: base.height,
            bg: [bg0, bg1],
            angle_deg: self.rng.random_range(0.0..360.0),
            shapes,
        }
    }

    /// Same background family, different content: the colors of the base's
    /// shapes are excluded, so the tag sets cannot overlap.
    fn draw_hard_negative(&mut self, base: &SceneSpec) -> SceneSpec {
        let banned: Vec<PaletteColor> = base.shapes.iter().map(|s| s.color).collect();
        let shapes = self.draw_shapes(Some(&banned));
        SceneSpec {
            shapes,
            ..base.clone()
        }
    }
}

impl Iterator for VisualStream {
    type Item = VisualBaseSpec;

    fn next(&mut self) -> Option<Self::Item> {
        let index = self.next_index;
        self.next_index += 1;

        let scene = self.draw_scene();
        // Drawn unconditionally so the stream position after asset `i`
        // never depends on which relatives asset `i` materialises.
        let lookalike = self.draw_lookalike(&scene);
        let semantic_sibling = self.draw_semantic_sibling(&scene);
        let hard_negative = self.draw_hard_negative(&scene);

        Some(VisualBaseSpec {
            index,
            scene,
            lookalike: index.is_multiple_of(2).then_some(lookalike),
            semantic_sibling: index.is_multiple_of(3).then_some(semantic_sibling),
            hard_negative: index.is_multiple_of(4).then_some(hard_negative),
        })
    }
}

pub struct VisualCorpusArgs {
    pub seed: u64,
    pub bases: u64,
    pub out: PathBuf,
}

pub fn run(args: VisualCorpusArgs) -> Result<()> {
    let manifest_path = args.out.join("manifest-visual.json");
    if let Some(existing) = read_visual_manifest(&manifest_path)?
        && existing.covers(args.seed, args.bases)
    {
        eprintln!(
            "benchgen: {} already holds seed={} bases={} — nothing to do",
            manifest_path.display(),
            existing.seed,
            existing.bases
        );
        return Ok(());
    }

    fs::create_dir_all(args.out.join("files"))
        .with_context(|| format!("cannot create files dir under {}", args.out.display()))?;
    fs::create_dir_all(args.out.join("texts"))
        .with_context(|| format!("cannot create texts dir under {}", args.out.display()))?;

    eprintln!(
        "benchgen: visual corpus seed={} bases={} out={}",
        args.seed,
        args.bases,
        args.out.display()
    );

    let started = Instant::now();
    let specs: Vec<VisualBaseSpec> = VisualStream::new(args.seed)
        .take(args.bases as usize)
        .collect();

    // Every base is independent; parallelism goes across bases and the
    // manifest folds back in stream order.
    let per_base: Vec<Result<Vec<VisualItem>>> = specs
        .par_iter()
        .map(|spec| materialise_base(&args.out, spec))
        .collect();

    let mut items = Vec::new();
    for result in per_base {
        items.extend(result?);
    }

    // The honest-failure controls: noise canvases with no counterpart, no
    // tags, and no caption. Their seeds derive from the corpus seed so the
    // whole directory remains a function of `(seed, generator_version)`.
    for i in 0..UNRELATED_IMAGES {
        let id = format!("u{i:02}");
        let (w, h) = DIMS[0];
        let png = to_png(&noise_image(args.seed ^ 0xC0FF_EE00 ^ i, w, h))?;
        let rel_path = format!("files/{id}.png");
        write_file(&args.out.join(&rel_path), &png)?;
        items.push(VisualItem {
            id,
            rel_path,
            role: VisualRole::Unrelated,
            base_id: None,
            tags_en: Vec::new(),
            tags_ja: Vec::new(),
            caption_en_path: None,
            caption_ja_path: None,
        });
    }

    let manifest = VisualManifest {
        schema: VISUAL_MANIFEST_SCHEMA.to_string(),
        seed: args.seed,
        generator_version: VISUAL_GENERATOR_VERSION.to_string(),
        bases: args.bases,
        item_count: items.len() as u64,
        items,
        unrelated_queries_en: unrelated_queries_en(),
        unrelated_queries_ja: unrelated_queries_ja(),
        generated_at_ms: now_ms(),
        elapsed_ms: started.elapsed().as_millis() as u64,
    };
    let json = serde_json::to_string_pretty(&manifest).context("cannot serialise manifest")?;
    fs::write(&manifest_path, json)
        .with_context(|| format!("cannot write {}", manifest_path.display()))?;

    eprintln!(
        "benchgen: wrote {} ({} items, {:.1}s)",
        manifest_path.display(),
        manifest.item_count,
        started.elapsed().as_secs_f64()
    );
    Ok(())
}

/// Render one base and all of its relatives. Files are written tmp+rename
/// and an existing non-empty file is accepted, the same resumability rule
/// as the bench tier.
fn materialise_base(out: &Path, spec: &VisualBaseSpec) -> Result<Vec<VisualItem>> {
    let base_id = spec.id();
    let img = render(&spec.scene)?;
    let base_png = to_png(&img)?;

    let mut items = Vec::with_capacity(8);
    let file = |name: &str, bytes: &[u8]| -> Result<String> {
        let rel = format!("files/{name}");
        write_file(&out.join(&rel), bytes)?;
        Ok(rel)
    };

    let tags_en = spec.scene.tags_en();
    let tags_ja = spec.scene.tags_ja();

    let caption_en_rel = format!("texts/{base_id}.en.txt");
    let caption_ja_rel = format!("texts/{base_id}.ja.txt");
    write_file(
        &out.join(&caption_en_rel),
        spec.scene.caption_en().as_bytes(),
    )?;
    write_file(
        &out.join(&caption_ja_rel),
        spec.scene.caption_ja().as_bytes(),
    )?;

    items.push(VisualItem {
        id: base_id.clone(),
        rel_path: file(&format!("{base_id}.png"), &base_png)?,
        role: VisualRole::Base,
        base_id: None,
        tags_en: tags_en.clone(),
        tags_ja: tags_ja.clone(),
        caption_en_path: Some(caption_en_rel),
        caption_ja_path: Some(caption_ja_rel),
    });

    let mut variant =
        |suffix: &str, role: VisualRole, bytes: &[u8], scene: &SceneSpec| -> Result<()> {
            let id = format!("{base_id}-{suffix}");
            let ext = if matches!(role, VisualRole::Recompress) {
                "jpg"
            } else {
                "png"
            };
            items.push(VisualItem {
                id: id.clone(),
                rel_path: file(&format!("{id}.{ext}"), bytes)?,
                role,
                base_id: Some(base_id.clone()),
                tags_en: scene.tags_en(),
                tags_ja: scene.tags_ja(),
                caption_en_path: None,
                caption_ja_path: None,
            });
            Ok(())
        };

    variant("copy", VisualRole::ExactCopy, &base_png, &spec.scene)?;
    variant(
        "half",
        VisualRole::Resize,
        &to_png(&resize(&img, RESIZE_FACTOR))?,
        &spec.scene,
    )?;
    variant(
        "jpeg",
        VisualRole::Recompress,
        &to_jpeg(&img, JPEG_QUALITY)?,
        &spec.scene,
    )?;
    variant(
        "crop",
        VisualRole::Crop,
        &to_png(&crop_center(&img, CROP_FRAC))?,
        &spec.scene,
    )?;

    if let Some(alike) = &spec.lookalike {
        variant(
            "alike",
            VisualRole::Lookalike,
            &to_png(&render(alike)?)?,
            alike,
        )?;
    }
    if let Some(sibling) = &spec.semantic_sibling {
        variant(
            "sibling",
            VisualRole::SemanticSibling,
            &to_png(&render(sibling)?)?,
            sibling,
        )?;
    }
    if let Some(negative) = &spec.hard_negative {
        variant(
            "negative",
            VisualRole::HardNegative,
            &to_png(&render(negative)?)?,
            negative,
        )?;
    }

    Ok(items)
}

fn write_file(path: &Path, bytes: &[u8]) -> Result<()> {
    if let Ok(meta) = fs::metadata(path)
        && meta.len() > 0
    {
        return Ok(());
    }
    let tmp = path.with_extension("part");
    fs::write(&tmp, bytes).with_context(|| format!("cannot write {}", tmp.display()))?;
    fs::rename(&tmp, path).with_context(|| format!("cannot finalise {}", path.display()))?;
    Ok(())
}

fn read_visual_manifest(path: &Path) -> Result<Option<VisualManifest>> {
    if !path.exists() {
        return Ok(None);
    }
    let text =
        fs::read_to_string(path).with_context(|| format!("cannot read {}", path.display()))?;
    let manifest: VisualManifest = serde_json::from_str(&text)
        .with_context(|| format!("{} is not a visual-corpus manifest", path.display()))?;
    Ok(Some(manifest))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stream_is_deterministic_in_the_seed() {
        let a: Vec<VisualBaseSpec> = VisualStream::new(7).take(5).collect();
        let b: Vec<VisualBaseSpec> = VisualStream::new(7).take(5).collect();
        assert_eq!(a, b);
        let c: Vec<VisualBaseSpec> = VisualStream::new(8).take(5).collect();
        assert_ne!(a, c, "a different seed is a different corpus");
    }

    #[test]
    fn relatives_follow_the_cadence() {
        let specs: Vec<VisualBaseSpec> = VisualStream::new(42).take(13).collect();
        for spec in &specs {
            assert_eq!(spec.lookalike.is_some(), spec.index % 2 == 0);
            assert_eq!(spec.semantic_sibling.is_some(), spec.index % 3 == 0);
            assert_eq!(spec.hard_negative.is_some(), spec.index % 4 == 0);
        }
    }

    #[test]
    fn relatives_relate_the_way_their_roles_claim() {
        for spec in VisualStream::new(42).take(20) {
            if let Some(alike) = &spec.lookalike {
                assert_eq!(alike.tags_en(), spec.scene.tags_en());
                assert_eq!(alike.bg, spec.scene.bg, "look-alike keeps the background");
            }
            if let Some(sibling) = &spec.semantic_sibling {
                assert_eq!(
                    sibling.tags_en(),
                    spec.scene.tags_en(),
                    "a semantic sibling shows the same describable content"
                );
                for c in sibling.bg {
                    assert!(
                        !spec.scene.bg.contains(&c),
                        "a semantic sibling changes the background family"
                    );
                }
            }
            if let Some(negative) = &spec.hard_negative {
                assert_eq!(
                    negative.bg, spec.scene.bg,
                    "hard negative keeps the background"
                );
                for tag in negative.tags_en() {
                    assert!(
                        !spec.scene.tags_en().contains(&tag),
                        "hard negative must not share a tag with its base: {tag}"
                    );
                }
            }
        }
    }

    #[test]
    fn shapes_stay_inside_the_crop_safe_region() {
        // The crop keeps [0.5 - f/2, 0.5 + f/2]; a shape at the widest
        // allowed center must still fit inside it whole.
        let crop_margin = (0.5 + CROP_FRAC / 2.0) - PLACEMENT.1;
        for spec in VisualStream::new(42).take(20) {
            for shape in &spec.scene.shapes {
                assert!((PLACEMENT.0..PLACEMENT.1).contains(&shape.cx));
                assert!((PLACEMENT.0..PLACEMENT.1).contains(&shape.cy));
                assert!(shape.size < crop_margin);
            }
        }
    }

    /// A tag the spec asserts must be visible in the pixels: no shape may
    /// occlude another, in any scene the stream produces. Chebyshev
    /// distance bounds the square, which bounds the other two kinds.
    #[test]
    fn no_shape_ever_occludes_another() {
        for spec in VisualStream::new(42).take(50) {
            let mut scenes = vec![&spec.scene];
            scenes.extend(spec.lookalike.as_ref());
            scenes.extend(spec.semantic_sibling.as_ref());
            scenes.extend(spec.hard_negative.as_ref());
            for scene in scenes {
                for (i, a) in scene.shapes.iter().enumerate() {
                    for b in scene.shapes.iter().skip(i + 1) {
                        let chebyshev = (a.cx - b.cx).abs().max((a.cy - b.cy).abs());
                        assert!(
                            chebyshev > a.size + b.size,
                            "shapes touch: d={chebyshev:.3} sizes={:.3}+{:.3}",
                            a.size,
                            b.size
                        );
                    }
                }
            }
        }
    }

    #[test]
    fn end_to_end_generates_files_relations_and_an_idempotent_manifest() {
        let dir = tempfile::tempdir().expect("tempdir");
        let args = || VisualCorpusArgs {
            seed: 42,
            bases: 3,
            out: dir.path().to_path_buf(),
        };
        run(args()).expect("generate");

        let manifest_path = dir.path().join("manifest-visual.json");
        let text = std::fs::read_to_string(&manifest_path).expect("manifest");
        let manifest: VisualManifest = serde_json::from_str(&text).expect("parse");
        assert!(manifest.covers(42, 3));
        assert!(!manifest.covers(43, 3));
        assert_eq!(
            manifest
                .items
                .iter()
                .filter(|i| i.role == VisualRole::Base)
                .count(),
            3
        );
        assert!(!manifest.unrelated_queries_en.is_empty());
        assert!(!manifest.unrelated_queries_ja.is_empty());

        for item in &manifest.items {
            let path = dir.path().join(&item.rel_path);
            assert!(path.exists(), "missing corpus file {}", item.rel_path);
            if item.role == VisualRole::Unrelated {
                assert!(item.tags_en.is_empty() && item.tags_ja.is_empty());
            } else {
                assert!(!item.tags_en.is_empty() && !item.tags_ja.is_empty());
            }
        }
        assert_eq!(
            manifest
                .items
                .iter()
                .filter(|i| i.role == VisualRole::Unrelated)
                .count() as u64,
            UNRELATED_IMAGES,
            "the honest-failure controls must exist"
        );

        // The exact copy is byte-identical to its base; the resize is not.
        let base = std::fs::read(dir.path().join("files/b0000.png")).expect("base");
        let copy = std::fs::read(dir.path().join("files/b0000-copy.png")).expect("copy");
        assert_eq!(base, copy);
        let half = std::fs::read(dir.path().join("files/b0000-half.png")).expect("half");
        assert_ne!(base, half);

        // Captions exist and read from the same ground truth.
        let caption = std::fs::read_to_string(dir.path().join("texts/b0000.en.txt")).expect("txt");
        assert!(caption.contains("gradient background"));

        // A second run with the same identity has nothing to do.
        run(args()).expect("idempotent rerun");
    }
}
